### ISSUE TITLE
README.md - OpenWRT Export Description Incorrect

### ISSUE THREAD

**Issue by preikschat** [GeekVisit/uproot#1]
Great software!

Using the example REAME.md writeup to export & convert the static leases for an OpenWRT router caused the utility to exit abnormally with error messages.  

Incorrect syntax:  _grep -hnr -A3 "config host" /etc/config/dhcp > static_leases.openwrt_

Suggest to change this to: _cat /etc/config/dhcp > static_leases.openwrt_

**Comment by GeekVisit** [comment]
It works for me but on my VM I am using an image which probably has more packages than most bare metal installs of OpenWrt and may be more recent. I think it has to do with the version of busybox that is packaged with the OpenWrt router.  I believe grep is either included in busybox or can be installed as a separate package. 

In any event, the step is actually unnecessary as uprt can extract the leases from /etc/config/dhcp without relying on grep so a user can actually just download dhcp and use it as the source file directly (which is why your cat command works). 

IMO it is preferable to delete the non-lease related configurations but it is unnecessary. 

I have revised the documentation and just committed that change.  Thanks!
